services:
  db:
    image: postgres:16
    container_name: stripe_clone_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stripe_clone
    volumes:
      - stripe_clone_pg:/var/lib/postgresql/data

volumes:
  stripe_clone_pg: